name: Test setup-ffmpeg
on:
  push:
    paths:
      - action.yaml
      - scripts/**
      - .github/workflows/test.yaml
      
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-latest]
        version: [release, master, "${{ vars.SPECIFIED_VERSION }}", "${{ vars.SPECIFIED_VERSION_MACOS }}"]
        exclude:
          - os: ubuntu-latest
            version: ${{ vars.SPECIFIED_VERSION_MACOS }}
          - os: ubuntu-24.04-arm
            version: ${{ vars.SPECIFIED_VERSION_MACOS }}
          - os: windows-latest
            version: ${{ vars.SPECIFIED_VERSION_MACOS }}
          - os: macos-latest
            version: ${{ vars.SPECIFIED_VERSION }}
            
    steps:
      - name: Setup FFmpeg using setup-ffmpeg
        uses: AnimMouse/setup-ffmpeg@main
        with:
          version: ${{ matrix.version }}
          
      - name: Test FFmpeg by checking version
        run: ffmpeg -version
        
      - name: Test FFprobe by checking version
        run: ffprobe -version
